spring:
  cloud:
    alicloud:
      access-key: LTAI4G1ZqsLSx7oBwZFkLLxS-bbb
      secret-key: 7SrS6Aa3UeebdLMaWynjWXwvYD1rto-bay
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mall-obj-ss
