spring:
  cloud:
    alicloud:
      access-key: LTAI4G1ZqsLSx7oBwZFkLLxS
      secret-key: 7SrS6Aa3UeebdLMaWynjWXwvYD1rto
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mall-obj